import pandas as pd
import numpy as np
import urllib.request
import os

def download_nab_dataset(url: str, dest_path: str) -> pd.DataFrame:
    """
    Downloads the NAB realAWSCloudwatch dataset to the local path and loads it.
    If URL is empty/None, it just tries to load the local path.
    """
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    if url and not os.path.exists(dest_path):
        print(f"Downloading from {url} to {dest_path}...")
        urllib.request.urlretrieve(url, dest_path)
    elif url:
        print(f"File already exists at {dest_path}.")
    else:
        print(f"Loading local dataset from {dest_path}.")
        
    df = pd.read_csv(dest_path)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values('timestamp').reset_index(drop=True)
    return df

def generate_labels(df: pd.DataFrame, value_col: str = 'value', window_size: int = 288, z_threshold: float = 3.0) -> pd.DataFrame:
    """
    Implements a rolling statistical threshold (dynamic Z-score) over a defined window
    to define an "incident" and generate ground-truth binary labels.
    
    window_size: 288 represents 24 hours of 5-minute interval data.
    z_threshold: Number of standard deviations to trigger an incident.
    """
    df = df.copy()
    
    # Calculate rolling mean and std
    rolling_mean = df[value_col].rolling(window=window_size, min_periods=window_size//2).mean()
    rolling_std = df[value_col].rolling(window=window_size, min_periods=window_size//2).std()
    
    # Calculate dynamic Z-score
    # Add small epsilon to std to avoid division by zero
    z_scores = (df[value_col] - rolling_mean) / (rolling_std + 1e-8)
    
    # Phase 4: Dynamic Pre-Processing
    actual_threshold = z_threshold
    # Ensure we get at least 5 anomaly points to train the model, drop threshold if necessary
    while (z_scores.abs() > actual_threshold).sum() < 5 and actual_threshold > 1.5:
        actual_threshold -= 0.5
        
    if actual_threshold != z_threshold:
        print(f"Dynamic Pre-Processing: Lowered Z-threshold from {z_threshold} to {actual_threshold:.1f} to gather sufficient incident examples.")
    
    # Label is 1 if absolute z-score > actual_threshold
    df['label'] = (z_scores.abs() > actual_threshold).astype(int)
    
    # Fill NA generated by rolling window with 0 (no incident)
    df['label'] = df['label'].fillna(0)
    
    return df
